
// This file was auto-generated by ML.NET Model Builder. 

using ModelSpamApp;

// Create single instance of sample data from first line of dataset for model input
ModelSpam.ModelInput sampleData = new ModelSpam.ModelInput()
{
    Content = @"Team meeting at 10 AM tomorrow",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual IsSpam with predicted IsSpam from sample data...\n\n");


Console.WriteLine($"Content: {@"Team meeting at 10 AM tomorrow"}");
Console.WriteLine($"IsSpam: {false}");


var sortedScoresWithLabel = ModelSpam.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

